/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSonhosRouteImport } from './routes/_authenticated/sonhos'
import { Route as AuthenticatedInvestimentosRouteImport } from './routes/_authenticated/investimentos'

const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/_authenticated/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSonhosRoute = AuthenticatedSonhosRouteImport.update({
  id: '/_authenticated/sonhos',
  path: '/sonhos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedInvestimentosRoute =
  AuthenticatedInvestimentosRouteImport.update({
    id: '/_authenticated/investimentos',
    path: '/investimentos',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/investimentos': typeof AuthenticatedInvestimentosRoute
  '/sonhos': typeof AuthenticatedSonhosRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesByTo {
  '/investimentos': typeof AuthenticatedInvestimentosRoute
  '/sonhos': typeof AuthenticatedSonhosRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/investimentos': typeof AuthenticatedInvestimentosRoute
  '/_authenticated/sonhos': typeof AuthenticatedSonhosRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/investimentos' | '/sonhos' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/investimentos' | '/sonhos' | '/'
  id:
    | '__root__'
    | '/_authenticated/investimentos'
    | '/_authenticated/sonhos'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedInvestimentosRoute: typeof AuthenticatedInvestimentosRoute
  AuthenticatedSonhosRoute: typeof AuthenticatedSonhosRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sonhos': {
      id: '/_authenticated/sonhos'
      path: '/sonhos'
      fullPath: '/sonhos'
      preLoaderRoute: typeof AuthenticatedSonhosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/investimentos': {
      id: '/_authenticated/investimentos'
      path: '/investimentos'
      fullPath: '/investimentos'
      preLoaderRoute: typeof AuthenticatedInvestimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedInvestimentosRoute: AuthenticatedInvestimentosRoute,
  AuthenticatedSonhosRoute: AuthenticatedSonhosRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
