/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SonhosRouteImport } from './routes/sonhos'
import { Route as InvestimentosRouteImport } from './routes/investimentos'
import { Route as IndexRouteImport } from './routes/index'

const SonhosRoute = SonhosRouteImport.update({
  id: '/sonhos',
  path: '/sonhos',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestimentosRoute = InvestimentosRouteImport.update({
  id: '/investimentos',
  path: '/investimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/investimentos': typeof InvestimentosRoute
  '/sonhos': typeof SonhosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/investimentos': typeof InvestimentosRoute
  '/sonhos': typeof SonhosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/investimentos': typeof InvestimentosRoute
  '/sonhos': typeof SonhosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/investimentos' | '/sonhos'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/investimentos' | '/sonhos'
  id: '__root__' | '/' | '/investimentos' | '/sonhos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InvestimentosRoute: typeof InvestimentosRoute
  SonhosRoute: typeof SonhosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sonhos': {
      id: '/sonhos'
      path: '/sonhos'
      fullPath: '/sonhos'
      preLoaderRoute: typeof SonhosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investimentos': {
      id: '/investimentos'
      path: '/investimentos'
      fullPath: '/investimentos'
      preLoaderRoute: typeof InvestimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InvestimentosRoute: InvestimentosRoute,
  SonhosRoute: SonhosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
